### ISSUE TITLE
Is it possible to automatically replenish custom labels?

### ISSUE THREAD

**Issue by kola-web** [olrtg/emmet-language-server#28]
Reference plan
"emmet.triggerExpansionOnTab": true, option in vscode

For example
enter
view press tab -> <view></view>

**Comment by olrtg** [comment]
Hey! Sorry for the late response.. busy with work. I don't understand what you are trying to achieve. Can explain me in more detail?

**Comment by kola-web** [comment]
The current emmet can only complete <div></div> <span></span> <p></p> these regular tags, but it cannot complete some custom tags such as <component></component>

**Comment by olrtg** [comment]
Such as? 👀 
Sorry it seems that your message got cut off

**Comment by kola-web** [comment]
抱歉

> The current emmet can only complete
> 
> these regular tags, but it cannot complete some custom tags such as

Feel sorry

view -> <view></view> <component></component> <a-modal></a-modal>
Non-html regular tags like this can also be completed normally.

**Comment by olrtg** [comment]
Oh! I see what you're saying now but I don't think this is the responsibility of this language server though. Maybe this is something that we can include in [nvim-emmet](https://github.com/olrtg/nvim-emmet) but I don't really know how this should be implemented because it'll depend on the completion plugin that you have.

Will move the close this issue to the other repo.

**Comment by kola-web** [comment]
Thank you for your help
