### ISSUE TITLE
abbr for <style> tag in HTML

### ISSUE THREAD

**Issue by nocis** [olrtg/emmet-language-server#35]
not sure how to resolve it without vscode parser, but I managed to resolve it via a stupid way.

I started 2 emmet-language-server instances for html file, one doComplete with html, one do css. you can easily config this via autocmd.
ref:https://github.com/microsoft/vscode/issues/28039

One flaw is that you will get 2 abbr suggestions messed your comp.

**Comment by olrtg** [comment]
Hey! I see, well I see what I can do this weekend.

**Comment by nocis** [comment]
> Hey! I see, well I see what I can do this weekend.

Thanks for replying!
I think the difficulty is that [microsoft/vscode-emmet-helper](https://github.com/microsoft/vscode-emmet-helper) only accept one syntax a time, they addressed this problem relaying on VSCode's internal parser to decide which syntax should be completed.

For nvim, I guess we need to either check if the position between <style> tags, or maybe treesitter has some magics...
Anyway, running 2 passes still is a viable option

**Comment by nocis** [comment]
Funny thing, seems like tsserver has the same page with us, it also does not work with js code inside HTML <script> tag, popular opinion suggest just "don't write inline JS in your html files"

**Comment by olrtg** [comment]
Hey @nocis. Yeah, this is something hard to handle in our language server as is. I know that there are some language servers like volar for vue, astro and svelte that use [volarjs](https://volarjs.dev/) for building those injections for `<style>` tags but that's because volar will make you bundle the emmet helper package.

I know also that it is possible to use treesitter for capturing those places and maybe we can implement something like vscode in https://github.com/olrtg/nvim-emmet. What I would try is, if we are on style tags pass the css language in real time to our language server else put the language as HTML again, although I'm not sure if that's possible.

If you would like to give it a shot maybe we can move this issue to the plugin repo and I can give you some assistance. That's not a case I run into often so I won't be implementing this soon.

Let me know what you think!

**Comment by nocis** [comment]
@olrtg Haha, thanks again for replying! We definitely can close this issue.

I did some research about this. Unfortunately, I think this feature hardly can be achieved from our side. Here are few considerations.

1. neovim lsp is not that flexible and nvim-lspconfig prefer attaching the client to buffer as it was open. And the filetype/syntax is setup at connection. Which means we cannot easily manage the clients for different languages.
2. treesitter supports injections and can identify css/js via script_element and style_element, the only way I think possible to use it is setup autocmd at insertleave/lsprequest_pending, then start OR send the lsp request to specified lsp clients.   
3. running 2 instances respectively for html and css still is a lightweight doable solution.

If you want to add smt for new plugin in the future, I would suggest we can run 2 instances, then merge the completions respect treesitter parse results. For anyone else want this extra feature, I would suggest running 2 instance through autocmd with different includeLanguages
