### ISSUE TITLE
how to add a new language?

### ISSUE THREAD

**Issue by chiefjester** [olrtg/emmet-language-server#37]
Hi, 

I'm using LazyVim; I'd like to know how to add Svelte.

I saw this PR (it seems like Svelte is removed)
https://github.com/neovim/nvim-lspconfig/pull/2914

But it seems that svelte language server is not implementing emmet for me?

I tried this config:
https://github.com/olrtg/emmet-language-server/issues/2#issue-1795226495

and added it in `autocommands.lua`

And I'm getting an error no global object on_attach and capabilities.

**Comment by olrtg** [comment]
Hey @chiefjester! Indeed, svelte was removed since the language server already bundles the emmet-helper package.

<img width="434" alt="Screenshot 2024-03-11 at 08 11 30" src="https://github.com/olrtg/emmet-language-server/assets/20072509/aad3ef96-3836-4bd6-a344-b6d76972a1f2">

And as you can see, I only have the svelte and prettierd language servers attached.

<img width="557" alt="Screenshot 2024-03-11 at 08 11 58" src="https://github.com/olrtg/emmet-language-server/assets/20072509/c1153ee0-0b24-430b-a649-3944d6ac3d9d">

Maybe share your config and I see if I can help.

**Comment by olrtg** [comment]
In my case, I see that Svelte does suggest some stuff on CSS, like `w` -> `width: |;` but not more specific abbreviations like `w100p`. So this is likely a problem with svelte's language server. Try raising the issue there. I'll close this too since this is outside of this project's scope.
