### ISSUE TITLE
Context aware completion 

### ISSUE THREAD

**Issue by HyperAfnan** [olrtg/emmet-language-server#42]
Hey I've been using your emmet language server from a long time I would like to thank you for creating such a great language server for neovim community 
I'm a frontend developer and when I am on a react project and writing react code in a js file 
I get a little bit annoyed how the language server shows emmet suggestions outside the jsx context
For example this is a `navbar.js` file
```js
import "../stylesheets/navbar.css";

function navbar() {
  return (
    <>
      <nav>
        <ul>Thing one</ul>
        <ul>Thing Two</ul>
        <ul>Thing Three</ul>
      </nav>
    </>
  );
}
export default navbar;

```

When my cursor is inside the jsx fragment `<>` It shows emmet suggestions that is fine
But it also shows emmet suggestions when I'm on the next line after `import` statement 
Isn't there any settings available to achieve context aware completion for emmet?

**Comment by olrtg** [comment]
@HyperAfnan well, in short this is something that I don't know how to solve and sadly doesn't seem to be possible ATM.
https://github.com/neovim/neovim/discussions/29477#discussioncomment-10082909.

This is something that some people already asked for in the past and even I, when I've tried zed (when I saw they were using my language server) I noticed that they had this mechanism implemented. If you ask me, I think there's a at least hacky way of implementing this but is out of my current skill and knowledge about the neovim API.

Will close this for now and maybe revisit this in the future if I find something useful in other projects or future versions of the neovim API.

Good luck!

**Comment by GNRSN** [comment]
Damm, I really enjoyed emmet in vscode and when making the switch to nvim I couldn't get emmet-ls into my workflow since it spamms completion in the entire buffer. When I found that there was a new emmet lsp project being actively maintained I got my hopes up from but from https://github.com/neovim/neovim/discussions/29477 it does indeed seem like there isn't much to do about it. 

I'm going to try experimenting with filtering completions instead, it could also be interesting if it was possible to turn down the priority of emmet completions unless they fully match. One of my main issues is that as soon as I type "d" anywhere in a `reactjavascript` buffer, the first (n) suggestions are all emmet for `div, dd, dl, dt, dir, del, dfn,...`, since tag names are so short, I never find myself needing to complete their name, only expand them.  

If anyone else has managed to find a workaround for this issue I'd very much appreciate some pointers ❤️

**Comment by GNRSN** [comment]
As a quick first effort, sorting any non exact emmet completions to the bottom made the experience a lot better for me. 

🔗 [If anybody is interested in this, here is the relevant diff in my dotfiles](https://github.com/GNRSN/dotfiles/commit/4c0694b980cce939451a9778daad9128ad15cfe9)

**Comment by AkisArou** [comment]
If anyone is interested, I got it working for blink.cmp

```lua
    providers = {
      lsp = {
        name = "LSP",
        module = "blink.cmp.sources.lsp",
        transform_items = function(ctx, items)
          if vim.bo[ctx.bufnr].filetype ~= "typescriptreact" then
            return items
          end

          return vim.tbl_filter(function(item)
            if item.client_name ~= "emmet_language_server" then
              return true
            end

            local node = vim.treesitter.get_node()
            while node do
              local t = node:type()
              if
                t == "jsx_element"
                or t == "jsx_self_closing_element"
                or t == "jsx_opening_element"
                or t == "jsx_fragment"
                or t == "jsx_expression"
              then
                return true
              end
              node = node:parent()
            end
            return false
          end, items)
        end,
      },
},
```
